version: '3'
services:
  rabbitmq:
    image: rabbitmq
    networks:
      - my_network
    ports:
      - "5672:5672"

  redis:
    image: redis
    networks:
      - my_network
    ports:
      - "6379:6379"

networks:
  my_network:
